from apps.udadmin.utils.ui_tools import UiInfo
from . import models as md

TestModelUi = UiInfo(
    model=md.TestModel,
    list_display=[
        "id",
        "big_int_field",
        "binary_field",
        "boolean_field",
        # "char_enum_field",
        # "char_field",
        # "date_field",
        # "date_time_field",
        # "decimal_field",
        # "float_field",
        # "int_enum_field",
        # "int_field",
        # "json_field",
        # "small_integer_field",
        # "text_field",
        # "time_delta_field",
        # "uuid_field",
    ],
    list_filter=[
        "id",
        "big_int_field",
        "binary_field",
        "boolean_field",
        "char_enum_field",
        "char_field",
        "date_field",
        "date_time_field",
        "decimal_field",
        "float_field",
        "int_enum_field",
        "int_field",
        "json_field",
        "small_integer_field",
        "text_field",
        "time_delta_field",
        "uuid_field",
    ],
    search_fields=[
        # "id",
        "char_field",
        # "decimal_field",
        # "float_field",
        # "uuid_field",
    ],
    # db_value_converters={"password": get_password_hash},
    # list_display=[
    #     "username",
    #     "password",
    #     "is_active",
    #     "is_superuser",
    #     "last_login",
    # ],
    # list_display=["*"],
    # readonly_fields=["created_at", "updated_at", "last_login"],
)
